name = "comodo-web-speed"
compatibility_date = "2024-09-12"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_VERSION = "22.16.0"

[build]
command = "npx @cloudflare/next-on-pages@1"